"""
services/mcp_services/mcp_service.py - 本地 MCP 服务入口。

不需要单独启动远程进程，业务代码可直接 import 并调用。
"""

from __future__ import annotations

from dataclasses import dataclass

from services.mcp_services.prompt_templates.base_extract_prompt_template import (
    SERVICE_NAME as BASE_EXTRACT_MCP_SERVICE,
    q as BASE_EXTRACT_MCP_Q,
    system_prompt as BASE_EXTRACT_MCP_SYSTEM_PROMPT,
    user_prompt as BASE_EXTRACT_MCP_USER_PROMPT,
)
from services.mcp_services.prompt_templates.bulk_solid_waste_extract_prompt_template import (
    SERVICE_NAME as BULK_SOLID_WASTE_EXTRACT_MCP_SERVICE,
    q as BULK_SOLID_WASTE_EXTRACT_MCP_Q,
    system_prompt as BULK_SOLID_WASTE_EXTRACT_MCP_SYSTEM_PROMPT,
    user_prompt as BULK_SOLID_WASTE_EXTRACT_MCP_USER_PROMPT,
)
from services.mcp_services.prompt_templates.energy_extract_prompt_template import (
    SERVICE_NAME as ENERGY_EXTRACT_MCP_SERVICE,
    q as ENERGY_EXTRACT_MCP_Q,
    system_prompt as ENERGY_EXTRACT_MCP_SYSTEM_PROMPT,
    user_prompt as ENERGY_EXTRACT_MCP_USER_PROMPT,
)
from services.mcp_services.prompt_templates.major_production_equipment_extract_prompt_template import (
    SERVICE_NAME as MAJOR_PRODUCTION_EQUIPMENT_EXTRACT_MCP_SERVICE,
    q as MAJOR_PRODUCTION_EQUIPMENT_EXTRACT_MCP_Q,
    system_prompt as MAJOR_PRODUCTION_EQUIPMENT_EXTRACT_MCP_SYSTEM_PROMPT,
    user_prompt as MAJOR_PRODUCTION_EQUIPMENT_EXTRACT_MCP_USER_PROMPT,
)
from services.mcp_services.prompt_templates.materials_extract_prompt_template import (
    SERVICE_NAME as MATERIALS_EXTRACT_MCP_SERVICE,
    q as MATERIALS_EXTRACT_MCP_Q,
    system_prompt as MATERIALS_EXTRACT_MCP_SYSTEM_PROMPT,
    user_prompt as MATERIALS_EXTRACT_MCP_USER_PROMPT,
)
from services.mcp_services.prompt_templates.pollutants_extract_prompt_template import (
    SERVICE_NAME as POLLUTANTS_EXTRACT_MCP_SERVICE,
    q as POLLUTANTS_EXTRACT_MCP_Q,
    system_prompt as POLLUTANTS_EXTRACT_MCP_SYSTEM_PROMPT,
    user_prompt as POLLUTANTS_EXTRACT_MCP_USER_PROMPT,
)
from services.mcp_services.prompt_templates.product_extract_prompt_template import (
    SERVICE_NAME as PRODUCT_EXTRACT_MCP_SERVICE,
    q as PRODUCT_EXTRACT_MCP_Q,
    system_prompt as PRODUCT_EXTRACT_MCP_SYSTEM_PROMPT,
    user_prompt as PRODUCT_EXTRACT_MCP_USER_PROMPT,
)
from services.mcp_services.prompt_templates.process_flow_extract_prompt_template import (
    SERVICE_NAME as PROCESS_FLOW_EXTRACT_MCP_SERVICE,
    q as PROCESS_FLOW_EXTRACT_MCP_Q,
    system_prompt as PROCESS_FLOW_EXTRACT_MCP_SYSTEM_PROMPT,
    user_prompt as PROCESS_FLOW_EXTRACT_MCP_USER_PROMPT,
)
from services.mcp_services.prompt_templates.regulation_policy_extract_prompt_template import (
    SERVICE_NAME as REGULATION_POLICY_EXTRACT_MCP_SERVICE,
    q as REGULATION_POLICY_EXTRACT_MCP_Q,
    system_prompt as REGULATION_POLICY_EXTRACT_MCP_SYSTEM_PROMPT,
    user_prompt as REGULATION_POLICY_EXTRACT_MCP_USER_PROMPT,
)
from services.mcp_services.prompt_templates.transformer_efficiency_benchmark_extract_prompt_template import (
    SERVICE_NAME as TRANSFORMER_EFFICIENCY_BENCHMARK_EXTRACT_MCP_SERVICE,
    q as TRANSFORMER_EFFICIENCY_BENCHMARK_EXTRACT_MCP_Q,
    system_prompt as TRANSFORMER_EFFICIENCY_BENCHMARK_EXTRACT_MCP_SYSTEM_PROMPT,
    user_prompt as TRANSFORMER_EFFICIENCY_BENCHMARK_EXTRACT_MCP_USER_PROMPT,
)
from services.mcp_services.prompt_templates.air_compressor_efficiency_benchmark_extract_prompt_template import (
    SERVICE_NAME as AIR_COMPRESSOR_EFFICIENCY_BENCHMARK_EXTRACT_MCP_SERVICE,
    q as AIR_COMPRESSOR_EFFICIENCY_BENCHMARK_EXTRACT_MCP_Q,
    system_prompt as AIR_COMPRESSOR_EFFICIENCY_BENCHMARK_EXTRACT_MCP_SYSTEM_PROMPT,
    user_prompt as AIR_COMPRESSOR_EFFICIENCY_BENCHMARK_EXTRACT_MCP_USER_PROMPT,
)
from services.mcp_services.prompt_templates.chiller_efficiency_benchmark_extract_prompt_template import (
    SERVICE_NAME as CHILLER_EFFICIENCY_BENCHMARK_EXTRACT_MCP_SERVICE,
    q as CHILLER_EFFICIENCY_BENCHMARK_EXTRACT_MCP_Q,
    system_prompt as CHILLER_EFFICIENCY_BENCHMARK_EXTRACT_MCP_SYSTEM_PROMPT,
    user_prompt as CHILLER_EFFICIENCY_BENCHMARK_EXTRACT_MCP_USER_PROMPT,
)
from services.mcp_services.prompt_templates.motor_efficiency_benchmark_extract_prompt_template import (
    SERVICE_NAME as MOTOR_EFFICIENCY_BENCHMARK_EXTRACT_MCP_SERVICE,
    q as MOTOR_EFFICIENCY_BENCHMARK_EXTRACT_MCP_Q,
    system_prompt as MOTOR_EFFICIENCY_BENCHMARK_EXTRACT_MCP_SYSTEM_PROMPT,
    user_prompt as MOTOR_EFFICIENCY_BENCHMARK_EXTRACT_MCP_USER_PROMPT,
)
from services.mcp_services.prompt_templates.energy_metering_instrument_extract_prompt_template import (
    SERVICE_NAME as ENERGY_METERING_INSTRUMENT_EXTRACT_MCP_SERVICE,
    q as ENERGY_METERING_INSTRUMENT_EXTRACT_MCP_Q,
    system_prompt as ENERGY_METERING_INSTRUMENT_EXTRACT_MCP_SYSTEM_PROMPT,
    user_prompt as ENERGY_METERING_INSTRUMENT_EXTRACT_MCP_USER_PROMPT,
)
from services.mcp_services.prompt_templates.management_system_status_extract_prompt_template import (
    SERVICE_NAME as MANAGEMENT_SYSTEM_STATUS_EXTRACT_MCP_SERVICE,
    q as MANAGEMENT_STATUS_EXTRACT_MCP_Q,
    system_prompt as MANAGEMENT_STATUS_EXTRACT_MCP_SYSTEM_PROMPT,
    user_prompt as MANAGEMENT_STATUS_EXTRACT_MCP_USER_PROMPT,
)
from services.mcp_services.prompt_templates.raw_material_consumption_extract_prompt_template import (
    SERVICE_NAME as RAW_MATERIAL_CONSUMPTION_EXTRACT_MCP_SERVICE,
    q as RAW_MATERIAL_CONSUMPTION_EXTRACT_MCP_Q,
    system_prompt as RAW_MATERIAL_CONSUMPTION_EXTRACT_MCP_SYSTEM_PROMPT,
    user_prompt as RAW_MATERIAL_CONSUMPTION_EXTRACT_MCP_USER_PROMPT,
)
from services.mcp_services.prompt_templates.green_material_usage_extract_prompt_template import (
    SERVICE_NAME as GREEN_MATERIAL_USAGE_EXTRACT_MCP_SERVICE,
    q as GREEN_MATERIAL_USAGE_EXTRACT_MCP_Q,
    system_prompt as GREEN_MATERIAL_USAGE_EXTRACT_MCP_SYSTEM_PROMPT,
    user_prompt as GREEN_MATERIAL_USAGE_EXTRACT_MCP_USER_PROMPT,
)
from services.mcp_services.prompt_templates.water_extract_prompt_template import (
    SERVICE_NAME as WATER_EXTRACT_MCP_SERVICE,
    q as WATER_EXTRACT_MCP_Q,
    system_prompt as WATER_EXTRACT_MCP_SYSTEM_PROMPT,
    user_prompt as WATER_EXTRACT_MCP_USER_PROMPT,
)
from services.mcp_services.prompt_templates.waste_gas_treatment_extract_prompt_template import (
    SERVICE_NAME as WASTE_GAS_TREATMENT_EXTRACT_MCP_SERVICE,
    q as WASTE_GAS_TREATMENT_EXTRACT_MCP_Q,
    system_prompt as WASTE_GAS_TREATMENT_EXTRACT_MCP_SYSTEM_PROMPT,
    user_prompt as WASTE_GAS_TREATMENT_EXTRACT_MCP_USER_PROMPT,
)
from services.mcp_services.prompt_templates.waste_gas_emission_total_extract_prompt_template import (
    SERVICE_NAME as WINESS_SCALE_EXTRACT_MCP_SERVICE,
    q as WINESS_SCALE_EXTRACT_MCP_Q,
    system_prompt as WINESS_SCALE_EXTRACT_MCP_SYSTEM_PROMPT,
    user_prompt as WINESS_SCALE_EXTRACT_MCP_USER_PROMPT,
)
from services.mcp_services.prompt_templates.solid_waste_generation_disposal_extract_prompt_template import (
    SERVICE_NAME as SOLID_WASTE_GENERATION_DISPOSAL_EXTRACT_MCP_SERVICE,
    q as SOLID_WASTE_GENERATION_DISPOSAL_EXTRACT_MCP_Q,
    system_prompt as SOLID_WASTE_GENERATION_DISPOSAL_EXTRACT_MCP_SYSTEM_PROMPT,
    user_prompt as SOLID_WASTE_GENERATION_DISPOSAL_EXTRACT_MCP_USER_PROMPT,
)
from services.mcp_services.prompt_templates.noise_monitoring_extract_prompt_template import (
    SERVICE_NAME as NOISE_MONITORING_EXTRACT_MCP_SERVICE,
    q as NOISE_MONITORING_EXTRACT_MCP_Q,
    system_prompt as NOISE_MONITORING_EXTRACT_MCP_SYSTEM_PROMPT,
    user_prompt as NOISE_MONITORING_EXTRACT_MCP_USER_PROMPT,
)
from services.mcp_services.prompt_templates.greenhouse_gas_emissions_extract_prompt_template import (
    SERVICE_NAME as GREENHOUSE_GAS_EMISSIONS_EXTRACT_MCP_SERVICE,
    q as GREENHOUSE_GAS_EMISSIONS_EXTRACT_MCP_Q,
    system_prompt as GREENHOUSE_GAS_EMISSIONS_EXTRACT_MCP_SYSTEM_PROMPT,
    user_prompt as GREENHOUSE_GAS_EMISSIONS_EXTRACT_MCP_USER_PROMPT,
)
from services.mcp_services.prompt_templates.land_intensification_extract_prompt_template import (
    SERVICE_NAME as LAND_INTENSIFICATION_EXTRACT_MCP_SERVICE,   
    q as LAND_INTENSIFICATION_EXTRACT_MCP_Q,
    system_prompt as LAND_INTENSIFICATION_EXTRACT_MCP_SYSTEM_PROMPT,
    user_prompt as LAND_INTENSIFICATION_EXTRACT_MCP_USER_PROMPT,
)
from services.mcp_services.prompt_templates.pollutant_emission_per_product_extract_prompt_template import (
    SERVICE_NAME as POLLUTANT_EMISSION_PER_PRODUCT_EXTRACT_MCP_SERVICE,
    q as POLLUTANT_EMISSION_PER_PRODUCT_EXTRACT_MCP_Q,
    system_prompt as POLLUTANT_EMISSION_PER_PRODUCT_EXTRACT_MCP_SYSTEM_PROMPT,
    user_prompt as POLLUTANT_EMISSION_PER_PRODUCT_EXTRACT_MCP_USER_PROMPT,
)
from services.mcp_services.prompt_templates.gas_emission_per_product_extract_prompt_template import (
    SERVICE_NAME as GAS_EMISSION_PER_PRODUCT_EXTRACT_MCP_SERVICE,
    q as GAS_EMISSION_PER_PRODUCT_EXTRACT_MCP_Q,
    system_prompt as GAS_EMISSION_PER_PRODUCT_EXTRACT_MCP_SYSTEM_PROMPT,
    user_prompt as GAS_EMISSION_PER_PRODUCT_EXTRACT_MCP_USER_PROMPT,
)
from services.mcp_services.prompt_templates.wastewater_emission_per_product_extract_prompt_template import (
    SERVICE_NAME as WASTewaterATER_EMISSION_PER_PRODUCT_EXTRACT_MCP_SERVICE,
    q as WASTewaterATER_EMISSION_PER_PRODUCT_EXTRACT_MCP_Q,
    system_prompt as WASTewaterATER_EMISSION_PER_PRODUCT_EXTRACT_MCP_SYSTEM_PROMPT,
    user_prompt as WASTewaterATER_EMISSION_PER_PRODUCT_EXTRACT_MCP_USER_PROMPT,
)
from services.mcp_services.prompt_templates.raw_material_consumption_per_product_extract_prompt_template import (
    SERVICE_NAME as RAW_MATERIAL_CONSUMPTION_PER_PRODUCT_EXTRACT_MCP_SERVICE,
    q as RAW_MATERIAL_CONSUMPTION_PER_PRODUCT_EXTRACT_MCP_Q,
    system_prompt as RAW_MATERIAL_CONSUMPTION_PER_PRODUCT_EXTRACT_MCP_SYSTEM_PROMPT,
    user_prompt as RAW_MATERIAL_CONSUMPTION_PER_PRODUCT_EXTRACT_MCP_USER_PROMPT,
)
from services.mcp_services.prompt_templates.water_consumption_per_product_extract_prompt_template import (
    SERVICE_NAME as WATER_CONSUMPTION_PER_PRODUCT_EXTRACT_MCP_SERVICE,
    q as WATER_CONSUMPTION_PER_PRODUCT_EXTRACT_MCP_Q,
    system_prompt as WATER_CONSUMPTION_PER_PRODUCT_EXTRACT_MCP_SYSTEM_PROMPT,
    user_prompt as WATER_CONSUMPTION_PER_PRODUCT_EXTRACT_MCP_USER_PROMPT,
)
from services.mcp_services.prompt_templates.energy_consumption_per_product_extract_prompt_template import (
    SERVICE_NAME as ENERGY_CONSUMPTION_PER_PRODUCT_EXTRACT_MCP_SERVICE,
    q as ENERGY_CONSUMPTION_PER_PRODUCT_EXTRACT_MCP_Q,
    system_prompt as ENERGY_CONSUMPTION_PER_PRODUCT_EXTRACT_MCP_SYSTEM_PROMPT,
    user_prompt as ENERGY_CONSUMPTION_PER_PRODUCT_EXTRACT_MCP_USER_PROMPT,
)
from services.mcp_services.prompt_templates.carbon_emission_per_product_extract_prompt_template import (
    SERVICE_NAME as CARBON_EMISSION_PER_PRODUCT_EXTRACT_MCP_SERVICE,
    q as CARBON_EMISSION_PER_PRODUCT_EXTRACT_MCP_Q,
    system_prompt as CARBON_EMISSION_PER_PRODUCT_EXTRACT_MCP_SYSTEM_PROMPT,
    user_prompt as CARBON_EMISSION_PER_PRODUCT_EXTRACT_MCP_USER_PROMPT,
)
from services.mcp_services.prompt_templates.qualification_certificate_info_extract_prompt_template import (
    SERVICE_NAME as QUALIFICATION_CERTIFICATE_INFO_EXTRACT_MCP_SERVICE,
    q as QUALIFICATION_CERTIFICATE_INFO_EXTRACT_MCP_Q,
    system_prompt as QUALIFICATION_CERTIFICATE_INFO_EXTRACT_MCP_SYSTEM_PROMPT,
    user_prompt as QUALIFICATION_CERTIFICATE_INFO_EXTRACT_MCP_USER_PROMPT,
)
from services.mcp_services.prompt_templates.raw_material_composition_extract_prompt_template import (
    SERVICE_NAME as RAW_MATERIAL_COMPOSITION_EXTRACT_MCP_SERVICE,
    q as RAW_MATERIAL_COMPOSITION_EXTRACT_MCP_Q,
    system_prompt as RAW_MATERIAL_COMPOSITION_EXTRACT_MCP_SYSTEM_PROMPT,
    user_prompt as RAW_MATERIAL_COMPOSITION_EXTRACT_MCP_USER_PROMPT,
)
from services.mcp_services.prompt_templates.material_composition_extract_prompt_template import (
    SERVICE_NAME as MATERIAL_COMPOSITION_EXTRACT_MCP_SERVICE,
    q as MATERIAL_COMPOSITION_EXTRACT_MCP_Q,
    system_prompt as MATERIAL_COMPOSITION_EXTRACT_MCP_SYSTEM_PROMPT,
    user_prompt as MATERIAL_COMPOSITION_EXTRACT_MCP_USER_PROMPT,
)
from services.mcp_services.prompt_templates.wastewater_pollutants_extract_prompt_template import (
    SERVICE_NAME as WASTEewaterATER_POLLUTANTS_EXTRACT_MCP_SERVICE,
    q as WASTEewaterATER_POLLUTANTS_EXTRACT_MCP_Q,
    system_prompt as WASTEewaterATER_POLLUTANTS_EXTRACT_MCP_SYSTEM_PROMPT,
    user_prompt as WASTEewaterATER_POLLUTANTS_EXTRACT_MCP_USER_PROMPT,
)


@dataclass(frozen=True)
class MCPService:
    name: str
    q: str
    system_prompt: str
    user_prompt: str


_SERVICES: dict[str, MCPService] = {
    BASE_EXTRACT_MCP_SERVICE: MCPService(
        name=BASE_EXTRACT_MCP_SERVICE,
        q=BASE_EXTRACT_MCP_Q,
        system_prompt=BASE_EXTRACT_MCP_SYSTEM_PROMPT,
        user_prompt=BASE_EXTRACT_MCP_USER_PROMPT,
    ),
    BULK_SOLID_WASTE_EXTRACT_MCP_SERVICE: MCPService(
        name=BULK_SOLID_WASTE_EXTRACT_MCP_SERVICE,
        q=BULK_SOLID_WASTE_EXTRACT_MCP_Q,
        system_prompt=BULK_SOLID_WASTE_EXTRACT_MCP_SYSTEM_PROMPT,
        user_prompt=BULK_SOLID_WASTE_EXTRACT_MCP_USER_PROMPT,
    ),
    ENERGY_EXTRACT_MCP_SERVICE: MCPService(
        name=ENERGY_EXTRACT_MCP_SERVICE,
        q=ENERGY_EXTRACT_MCP_Q,
        system_prompt=ENERGY_EXTRACT_MCP_SYSTEM_PROMPT,
        user_prompt=ENERGY_EXTRACT_MCP_USER_PROMPT,
    ),
    MAJOR_PRODUCTION_EQUIPMENT_EXTRACT_MCP_SERVICE: MCPService(
        name=MAJOR_PRODUCTION_EQUIPMENT_EXTRACT_MCP_SERVICE,
        q=MAJOR_PRODUCTION_EQUIPMENT_EXTRACT_MCP_Q,
        system_prompt=MAJOR_PRODUCTION_EQUIPMENT_EXTRACT_MCP_SYSTEM_PROMPT,
        user_prompt=MAJOR_PRODUCTION_EQUIPMENT_EXTRACT_MCP_USER_PROMPT,
    ),
    MATERIALS_EXTRACT_MCP_SERVICE: MCPService(
        name=MATERIALS_EXTRACT_MCP_SERVICE,
        q=MATERIALS_EXTRACT_MCP_Q,
        system_prompt=MATERIALS_EXTRACT_MCP_SYSTEM_PROMPT,
        user_prompt=MATERIALS_EXTRACT_MCP_USER_PROMPT,
    ),
    POLLUTANTS_EXTRACT_MCP_SERVICE: MCPService(
        name=POLLUTANTS_EXTRACT_MCP_SERVICE,
        q=POLLUTANTS_EXTRACT_MCP_Q,
        system_prompt=POLLUTANTS_EXTRACT_MCP_SYSTEM_PROMPT,
        user_prompt=POLLUTANTS_EXTRACT_MCP_USER_PROMPT,
    ),
    PRODUCT_EXTRACT_MCP_SERVICE: MCPService(
        name=PRODUCT_EXTRACT_MCP_SERVICE,
        q=PRODUCT_EXTRACT_MCP_Q,
        system_prompt=PRODUCT_EXTRACT_MCP_SYSTEM_PROMPT,
        user_prompt=PRODUCT_EXTRACT_MCP_USER_PROMPT,
    ),
    PROCESS_FLOW_EXTRACT_MCP_SERVICE: MCPService(
        name=PROCESS_FLOW_EXTRACT_MCP_SERVICE,
        q=PROCESS_FLOW_EXTRACT_MCP_Q,
        system_prompt=PROCESS_FLOW_EXTRACT_MCP_SYSTEM_PROMPT,
        user_prompt=PROCESS_FLOW_EXTRACT_MCP_USER_PROMPT,
    ),
    REGULATION_POLICY_EXTRACT_MCP_SERVICE: MCPService(
        name=REGULATION_POLICY_EXTRACT_MCP_SERVICE,
        q=REGULATION_POLICY_EXTRACT_MCP_Q,
        system_prompt=REGULATION_POLICY_EXTRACT_MCP_SYSTEM_PROMPT,
        user_prompt=REGULATION_POLICY_EXTRACT_MCP_USER_PROMPT,
    ),
    TRANSFORMER_EFFICIENCY_BENCHMARK_EXTRACT_MCP_SERVICE: MCPService(
        name=TRANSFORMER_EFFICIENCY_BENCHMARK_EXTRACT_MCP_SERVICE,
        q=TRANSFORMER_EFFICIENCY_BENCHMARK_EXTRACT_MCP_Q,
        system_prompt=TRANSFORMER_EFFICIENCY_BENCHMARK_EXTRACT_MCP_SYSTEM_PROMPT,
        user_prompt=TRANSFORMER_EFFICIENCY_BENCHMARK_EXTRACT_MCP_USER_PROMPT,
    ),
    AIR_COMPRESSOR_EFFICIENCY_BENCHMARK_EXTRACT_MCP_SERVICE: MCPService(
        name=AIR_COMPRESSOR_EFFICIENCY_BENCHMARK_EXTRACT_MCP_SERVICE,
        q=AIR_COMPRESSOR_EFFICIENCY_BENCHMARK_EXTRACT_MCP_Q,
        system_prompt=AIR_COMPRESSOR_EFFICIENCY_BENCHMARK_EXTRACT_MCP_SYSTEM_PROMPT,
        user_prompt=AIR_COMPRESSOR_EFFICIENCY_BENCHMARK_EXTRACT_MCP_USER_PROMPT,
    ),
    CHILLER_EFFICIENCY_BENCHMARK_EXTRACT_MCP_SERVICE: MCPService(
        name=CHILLER_EFFICIENCY_BENCHMARK_EXTRACT_MCP_SERVICE,
        q=CHILLER_EFFICIENCY_BENCHMARK_EXTRACT_MCP_Q,
        system_prompt=CHILLER_EFFICIENCY_BENCHMARK_EXTRACT_MCP_SYSTEM_PROMPT,
        user_prompt=CHILLER_EFFICIENCY_BENCHMARK_EXTRACT_MCP_USER_PROMPT,
    ),
    MOTOR_EFFICIENCY_BENCHMARK_EXTRACT_MCP_SERVICE: MCPService(
        name=MOTOR_EFFICIENCY_BENCHMARK_EXTRACT_MCP_SERVICE,
        q=MOTOR_EFFICIENCY_BENCHMARK_EXTRACT_MCP_Q,
        system_prompt=MOTOR_EFFICIENCY_BENCHMARK_EXTRACT_MCP_SYSTEM_PROMPT,
        user_prompt=MOTOR_EFFICIENCY_BENCHMARK_EXTRACT_MCP_USER_PROMPT,
    ),
    ENERGY_METERING_INSTRUMENT_EXTRACT_MCP_SERVICE: MCPService(
        name=ENERGY_METERING_INSTRUMENT_EXTRACT_MCP_SERVICE,
        q=ENERGY_METERING_INSTRUMENT_EXTRACT_MCP_Q,
        system_prompt=ENERGY_METERING_INSTRUMENT_EXTRACT_MCP_SYSTEM_PROMPT,
        user_prompt=ENERGY_METERING_INSTRUMENT_EXTRACT_MCP_USER_PROMPT,
    ),
    MANAGEMENT_SYSTEM_STATUS_EXTRACT_MCP_SERVICE: MCPService(
        name=MANAGEMENT_SYSTEM_STATUS_EXTRACT_MCP_SERVICE,
        q=MANAGEMENT_STATUS_EXTRACT_MCP_Q,
        system_prompt=MANAGEMENT_STATUS_EXTRACT_MCP_SYSTEM_PROMPT,
        user_prompt=MANAGEMENT_STATUS_EXTRACT_MCP_USER_PROMPT,
    ),
    RAW_MATERIAL_CONSUMPTION_EXTRACT_MCP_SERVICE: MCPService(
        name=RAW_MATERIAL_CONSUMPTION_EXTRACT_MCP_SERVICE,
        q=RAW_MATERIAL_CONSUMPTION_EXTRACT_MCP_Q,
        system_prompt=RAW_MATERIAL_CONSUMPTION_EXTRACT_MCP_SYSTEM_PROMPT,
        user_prompt=RAW_MATERIAL_CONSUMPTION_EXTRACT_MCP_USER_PROMPT,
    ),
    GREEN_MATERIAL_USAGE_EXTRACT_MCP_SERVICE: MCPService(
        name=GREEN_MATERIAL_USAGE_EXTRACT_MCP_SERVICE,
        q=GREEN_MATERIAL_USAGE_EXTRACT_MCP_Q,
        system_prompt=GREEN_MATERIAL_USAGE_EXTRACT_MCP_SYSTEM_PROMPT,
        user_prompt=GREEN_MATERIAL_USAGE_EXTRACT_MCP_USER_PROMPT,
    ),
    WATER_EXTRACT_MCP_SERVICE: MCPService(
        name=WATER_EXTRACT_MCP_SERVICE,
        q=WATER_EXTRACT_MCP_Q,
        system_prompt=WATER_EXTRACT_MCP_SYSTEM_PROMPT,
        user_prompt=WATER_EXTRACT_MCP_USER_PROMPT,
    ),
    WASTE_GAS_TREATMENT_EXTRACT_MCP_SERVICE: MCPService(
        name=WASTE_GAS_TREATMENT_EXTRACT_MCP_SERVICE,
        q=WASTE_GAS_TREATMENT_EXTRACT_MCP_Q,
        system_prompt=WASTE_GAS_TREATMENT_EXTRACT_MCP_SYSTEM_PROMPT,
        user_prompt=WASTE_GAS_TREATMENT_EXTRACT_MCP_USER_PROMPT,
    ),
    WINESS_SCALE_EXTRACT_MCP_SERVICE: MCPService(
        name=WINESS_SCALE_EXTRACT_MCP_SERVICE,
        q=WINESS_SCALE_EXTRACT_MCP_Q,
        system_prompt=WINESS_SCALE_EXTRACT_MCP_SYSTEM_PROMPT,
        user_prompt=WINESS_SCALE_EXTRACT_MCP_USER_PROMPT,
    ),
    SOLID_WASTE_GENERATION_DISPOSAL_EXTRACT_MCP_SERVICE: MCPService(
        name=SOLID_WASTE_GENERATION_DISPOSAL_EXTRACT_MCP_SERVICE,
        q=SOLID_WASTE_GENERATION_DISPOSAL_EXTRACT_MCP_Q,
        system_prompt=SOLID_WASTE_GENERATION_DISPOSAL_EXTRACT_MCP_SYSTEM_PROMPT,
        user_prompt=SOLID_WASTE_GENERATION_DISPOSAL_EXTRACT_MCP_USER_PROMPT,
    ),
    NOISE_MONITORING_EXTRACT_MCP_SERVICE: MCPService(
        name=NOISE_MONITORING_EXTRACT_MCP_SERVICE,
        q=NOISE_MONITORING_EXTRACT_MCP_Q,
        system_prompt=NOISE_MONITORING_EXTRACT_MCP_SYSTEM_PROMPT,
        user_prompt=NOISE_MONITORING_EXTRACT_MCP_USER_PROMPT,
    ),
    GREENHOUSE_GAS_EMISSIONS_EXTRACT_MCP_SERVICE: MCPService(
        name=GREENHOUSE_GAS_EMISSIONS_EXTRACT_MCP_SERVICE,
        q=GREENHOUSE_GAS_EMISSIONS_EXTRACT_MCP_Q,
        system_prompt=GREENHOUSE_GAS_EMISSIONS_EXTRACT_MCP_SYSTEM_PROMPT,
        user_prompt=GREENHOUSE_GAS_EMISSIONS_EXTRACT_MCP_USER_PROMPT,
    ),
    LAND_INTENSIFICATION_EXTRACT_MCP_SERVICE: MCPService(
        name=LAND_INTENSIFICATION_EXTRACT_MCP_SERVICE,   
        q=LAND_INTENSIFICATION_EXTRACT_MCP_Q,
        system_prompt=LAND_INTENSIFICATION_EXTRACT_MCP_SYSTEM_PROMPT,
        user_prompt=LAND_INTENSIFICATION_EXTRACT_MCP_USER_PROMPT,
    ),
    POLLUTANT_EMISSION_PER_PRODUCT_EXTRACT_MCP_SERVICE: MCPService(
        name=POLLUTANT_EMISSION_PER_PRODUCT_EXTRACT_MCP_SERVICE,
        q=POLLUTANT_EMISSION_PER_PRODUCT_EXTRACT_MCP_Q,
        system_prompt=POLLUTANT_EMISSION_PER_PRODUCT_EXTRACT_MCP_SYSTEM_PROMPT,
        user_prompt=POLLUTANT_EMISSION_PER_PRODUCT_EXTRACT_MCP_USER_PROMPT,
    ),
    GAS_EMISSION_PER_PRODUCT_EXTRACT_MCP_SERVICE: MCPService(
        name=GAS_EMISSION_PER_PRODUCT_EXTRACT_MCP_SERVICE,
        q=GAS_EMISSION_PER_PRODUCT_EXTRACT_MCP_Q,
        system_prompt=GAS_EMISSION_PER_PRODUCT_EXTRACT_MCP_SYSTEM_PROMPT,
        user_prompt=GAS_EMISSION_PER_PRODUCT_EXTRACT_MCP_USER_PROMPT,
    ),
    WASTewaterATER_EMISSION_PER_PRODUCT_EXTRACT_MCP_SERVICE: MCPService(
        name=WASTewaterATER_EMISSION_PER_PRODUCT_EXTRACT_MCP_SERVICE,
        q=WASTewaterATER_EMISSION_PER_PRODUCT_EXTRACT_MCP_Q,
        system_prompt=WASTewaterATER_EMISSION_PER_PRODUCT_EXTRACT_MCP_SYSTEM_PROMPT,
        user_prompt=WASTewaterATER_EMISSION_PER_PRODUCT_EXTRACT_MCP_USER_PROMPT,
    ),
    RAW_MATERIAL_CONSUMPTION_PER_PRODUCT_EXTRACT_MCP_SERVICE: MCPService(
        name=RAW_MATERIAL_CONSUMPTION_PER_PRODUCT_EXTRACT_MCP_SERVICE,
        q=RAW_MATERIAL_CONSUMPTION_PER_PRODUCT_EXTRACT_MCP_Q,
        system_prompt=RAW_MATERIAL_CONSUMPTION_PER_PRODUCT_EXTRACT_MCP_SYSTEM_PROMPT,
        user_prompt=RAW_MATERIAL_CONSUMPTION_PER_PRODUCT_EXTRACT_MCP_USER_PROMPT,
    ),
    WATER_CONSUMPTION_PER_PRODUCT_EXTRACT_MCP_SERVICE: MCPService(
        name=WATER_CONSUMPTION_PER_PRODUCT_EXTRACT_MCP_SERVICE,
        q=WATER_CONSUMPTION_PER_PRODUCT_EXTRACT_MCP_Q,
        system_prompt=WATER_CONSUMPTION_PER_PRODUCT_EXTRACT_MCP_SYSTEM_PROMPT,
        user_prompt=WATER_CONSUMPTION_PER_PRODUCT_EXTRACT_MCP_USER_PROMPT,
    ),
    ENERGY_CONSUMPTION_PER_PRODUCT_EXTRACT_MCP_SERVICE: MCPService(
        name=ENERGY_CONSUMPTION_PER_PRODUCT_EXTRACT_MCP_SERVICE,
        q=ENERGY_CONSUMPTION_PER_PRODUCT_EXTRACT_MCP_Q,
        system_prompt=ENERGY_CONSUMPTION_PER_PRODUCT_EXTRACT_MCP_SYSTEM_PROMPT,
        user_prompt=ENERGY_CONSUMPTION_PER_PRODUCT_EXTRACT_MCP_USER_PROMPT,
    ),
    CARBON_EMISSION_PER_PRODUCT_EXTRACT_MCP_SERVICE: MCPService(
        name=CARBON_EMISSION_PER_PRODUCT_EXTRACT_MCP_SERVICE,
        q=CARBON_EMISSION_PER_PRODUCT_EXTRACT_MCP_Q,
        system_prompt=CARBON_EMISSION_PER_PRODUCT_EXTRACT_MCP_SYSTEM_PROMPT,
        user_prompt=CARBON_EMISSION_PER_PRODUCT_EXTRACT_MCP_USER_PROMPT,
    ),
    QUALIFICATION_CERTIFICATE_INFO_EXTRACT_MCP_SERVICE: MCPService(
        name=QUALIFICATION_CERTIFICATE_INFO_EXTRACT_MCP_SERVICE,
        q=QUALIFICATION_CERTIFICATE_INFO_EXTRACT_MCP_Q,
        system_prompt=QUALIFICATION_CERTIFICATE_INFO_EXTRACT_MCP_SYSTEM_PROMPT,
        user_prompt=QUALIFICATION_CERTIFICATE_INFO_EXTRACT_MCP_USER_PROMPT,
    ),
    RAW_MATERIAL_COMPOSITION_EXTRACT_MCP_SERVICE: MCPService(
        name=RAW_MATERIAL_COMPOSITION_EXTRACT_MCP_SERVICE,
        q=RAW_MATERIAL_COMPOSITION_EXTRACT_MCP_Q,
        system_prompt=RAW_MATERIAL_COMPOSITION_EXTRACT_MCP_SYSTEM_PROMPT,
        user_prompt=RAW_MATERIAL_COMPOSITION_EXTRACT_MCP_USER_PROMPT,
    ),
    MATERIAL_COMPOSITION_EXTRACT_MCP_SERVICE: MCPService(
        name=MATERIAL_COMPOSITION_EXTRACT_MCP_SERVICE,
        q=MATERIAL_COMPOSITION_EXTRACT_MCP_Q,
        system_prompt=MATERIAL_COMPOSITION_EXTRACT_MCP_SYSTEM_PROMPT,
        user_prompt=MATERIAL_COMPOSITION_EXTRACT_MCP_USER_PROMPT,
    ),
    WASTEewaterATER_POLLUTANTS_EXTRACT_MCP_SERVICE: MCPService(
        name=WASTEewaterATER_POLLUTANTS_EXTRACT_MCP_SERVICE,
        q=WASTEewaterATER_POLLUTANTS_EXTRACT_MCP_Q,
        system_prompt=WASTEewaterATER_POLLUTANTS_EXTRACT_MCP_SYSTEM_PROMPT,
        user_prompt=WASTEewaterATER_POLLUTANTS_EXTRACT_MCP_USER_PROMPT,
    ),
}


def get_service(service_name: str) -> MCPService:
    service = _SERVICES.get(service_name)
    if not service:
        raise KeyError(f"未知模板服务: {service_name}")
    return service


def list_service_names() -> list[str]:
    return sorted(_SERVICES.keys())

